// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/menu/auth/login": {
            "post": {
                "description": "Frontend-facing login endpoint backed by platform identity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login menu user",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/auth/register": {
            "post": {
                "description": "Frontend-facing register endpoint. Menu orchestrates platform user/org creation and optional signup bonus issuance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register menu user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/auth/session": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Resolve current authenticated user, current organization, and current credits balance for frontend bootstrap.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/codes/{code}/resolve": {
            "get": {
                "description": "Resolve a referral code before signup and return reward policy details for the current Menu product.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "Resolve referral code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Referral code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/codes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List referral codes owned by the current organization with optional program and status filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "List referral codes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Program code filter",
                        "name": "program_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Code status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new referral code for the current organization and selected program.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "Create referral code",
                "parameters": [
                    {
                        "description": "Create referral code request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_referral.CreateCodeInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/codes/ensure": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Idempotently ensure the current organization has an active referral code for the selected program.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "Ensure referral code",
                "parameters": [
                    {
                        "description": "Ensure referral code request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_referral.CreateCodeInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/commissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List referral commissions for the current organization with optional status filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "List commissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Commission status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/commissions/redeem": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Redeem earned referral commissions into the configured Menu reward asset for the current organization.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "Redeem commissions",
                "parameters": [
                    {
                        "description": "Redeem commissions request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_referral.RedeemInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/conversions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List referral conversions for the current organization with optional status filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "List referral conversions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversion status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/me/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Load current organization referral overview including programs, codes, conversions, commissions, and aggregate commission metrics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "Get referral overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversion status filter",
                        "name": "conversion_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Commission status filter",
                        "name": "commission_status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/referrals/programs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List active or filtered referral programs available to the current Menu product.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "summary": "List referral programs",
                "parameters": [
                    {
                        "type": "string",
                        "default": "active",
                        "description": "Program status filter",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/user/activities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query activity and history records for the current authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "List user activities",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/user/credits": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query current credits balance and current plan view for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get credits and plan detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query current user profile and current restaurant/org view for frontend settings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update current user name, restaurant name, and language preference through Menu orchestration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Profile update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user.UpdateProfileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/menu-service_pkg_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_modules_auth.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "internal_modules_auth.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "restaurant_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "referral_code": {
                    "type": "string"
                },
                "restaurant_name": {
                    "type": "string",
                    "minLength": 2
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_modules_referral.CreateCodeInput": {
            "type": "object",
            "required": [
                "program_code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "program_code": {
                    "type": "string"
                }
            }
        },
        "internal_modules_referral.RedeemInput": {
            "type": "object",
            "properties": {
                "commission_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "metadata": {
                    "type": "string"
                }
            }
        },
        "internal_modules_user.UpdateProfileInput": {
            "type": "object",
            "properties": {
                "language_preference": {
                    "type": "string",
                    "enum": [
                        "en",
                        "zh",
                        "th"
                    ]
                },
                "name": {
                    "type": "string"
                },
                "restaurant_name": {
                    "type": "string"
                }
            }
        },
        "menu-service_pkg_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/menu-service_pkg_response.ResponseCode"
                },
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "error_hint": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu-service_pkg_response.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "menu-service_pkg_response.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "menu-service_pkg_response.ResponseCode": {
            "type": "integer",
            "enum": [
                0,
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                1006,
                1007,
                1008,
                2000,
                2001,
                5000,
                5001,
                5002,
                5003
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeInvalidParameter",
                "CodeUnauthorized",
                "CodeBadRequest",
                "CodeForbidden",
                "CodeNotFound",
                "CodeConflict",
                "CodeMethodNotAllowed",
                "CodeTooManyRequests",
                "CodeMissingParameter",
                "CodeBusinessError",
                "CodeExternalDependency",
                "CodeInternalError",
                "CodeDatabaseError",
                "CodeThirdPartyError",
                "CodeServiceUnavailable"
            ]
        },
        "menu-service_pkg_response.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/menu-service_pkg_response.ResponseCode"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Menu Backend API",
	Description:      "Frontend-facing APIs for Menu AI P0 auth, session, and credits flows.\nProduct workflows stay in menu-backend while shared identity/org/wallet truth stays in v-platform-backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
